print("Welcome to the Space Travel Calculator!")
distance = int(input("Enter the distance to the celestial object in light years"))
speed = int(input("Enter the spacecraft speed in fraction of the speed of light"))
time = (distance/speed)
print("It would take", time, "light years to reach your destination with your spacecraft!")